# Generated by Django 6.0.1 on 2026-01-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование материала')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Количество')),
                ('unit', models.CharField(choices=[('шт', 'штук'), ('т', 'тонн'), ('кг', 'килограммов'), ('м', 'метров'), ('м³', 'кубических метров'), ('л', 'литров')], max_length=10, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='При достижении этого уровня требуется пополнение', max_digits=15, verbose_name='Минимальный запас')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Место хранения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
    ]
