# Generated by Django 6.0.1 on 2026-01-30 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=300, verbose_name='Номенклатура')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Количество')),
                ('unit', models.CharField(choices=[('шт', 'штук'), ('т', 'тонн'), ('кг', 'килограммов'), ('м', 'метров'), ('м³', 'кубических метров'), ('л', 'литров')], max_length=10, verbose_name='Единица измерения')),
                ('plan_type', models.CharField(choices=[('planned', 'Плановая'), ('unplanned', 'Внеплановая'), ('urgent', 'Срочная')], default='planned', max_length=20, verbose_name='План')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Отклонена'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('budget_article', models.CharField(choices=[('capex', 'CAPEX (Капитальные затраты)'), ('opex', 'OPEX (Операционные затраты)'), ('repair', 'Ремонтные работы'), ('safety', 'Охрана труда и ТБ'), ('other', 'Прочее')], default='opex', max_length=20, verbose_name='Статья бюджета')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(blank=True, verbose_name='Описание/Примечание')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
                'ordering': ['-created_at'],
            },
        ),
    ]
