# Generated by Django 6.0.1 on 2026-01-31 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='purchase_files/%Y/%m/', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Максимальная цена'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='plan_year',
            field=models.IntegerField(choices=[(2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')], default=2026, verbose_name='Год плана'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='procurement.material', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='plan_type',
            field=models.CharField(choices=[('planned', 'Плановая'), ('unplanned', 'Внеплановая'), ('urgent', 'Срочная')], default='planned', max_length=20, verbose_name='Тип плана'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланирована'), ('pending', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Отклонена'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
