# Generated by Django 6.0.1 on 2026-01-31 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_purchaserequest_attachment_purchaserequest_max_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='plan_year',
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Минимальный запас'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.material', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='plan_type',
            field=models.CharField(choices=[('plan_2026', 'План закупок на 2026 год'), ('plan_2027', 'План закупок на 2027 год'), ('plan_2028', 'План закупок на 2028 год'), ('plan_2029', 'План закупок на 2029 год'), ('plan_2030', 'План закупок на 2030 год'), ('plan_2031', 'План закупок на 2031 год'), ('unplanned', 'Внеплановая закупка'), ('urgent', 'Срочная закупка')], max_length=20, verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
    ]
