# Generated by Django 6.0.1 on 2026-01-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_remove_purchaserequest_plan_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='plan_type',
            field=models.CharField(choices=[('plan_2026', 'План закупок на 2026 год'), ('plan_2027', 'План закупок на 2027 год'), ('plan_2028', 'План закупок на 2028 год'), ('plan_2029', 'План закупок на 2029 год'), ('plan_2030', 'План закупок на 2030 год'), ('plan_2031', 'План закупок на 2031 год')], max_length=20, verbose_name='План'),
        ),
    ]
