# Generated by Django 6.0.1 on 2026-02-01 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_purchaserequest_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=20, verbose_name='План')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('decision', models.CharField(blank=True, choices=[('approved', 'Согласовано'), ('rejected', 'Отклонено')], max_length=20, verbose_name='Решение')),
                ('document', models.FileField(blank=True, null=True, upload_to='approval_docs/%Y/%m/', verbose_name='Документ')),
                ('status', models.CharField(choices=[('pending', 'На согласовании'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
            ],
            options={
                'verbose_name': 'Запись согласования',
                'verbose_name_plural': 'История согласования',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=20, verbose_name='План')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
            ],
            options={
                'verbose_name': 'Согласующий по плану',
                'verbose_name_plural': 'Согласующие по планам',
                'unique_together': {('plan_type', 'user')},
            },
        ),
    ]
