# Generated by Django 6.0.1 on 2026-02-01 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_planapprovalhistory_planapprover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=300, verbose_name='Название конкурса')),
                ('status', models.CharField(choices=[('preparation', 'Подготовка'), ('active', 'Активный'), ('closed', 'Закрыт'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='preparation', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала конкурса')),
                ('submission_deadline', models.DateTimeField(verbose_name='Срок подачи предложений')),
                ('publication_type', models.CharField(choices=[('open', 'Открытый'), ('closed', 'Закрытый')], default='open', max_length=10, verbose_name='Тип публикации')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Общая цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
