# Generated by Django 6.0.1 on 2026-02-01 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_tender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='total_price',
        ),
        migrations.AddField(
            model_name='tender',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tenders', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='tender',
            name='delivery_term',
            field=models.CharField(blank=True, max_length=200, verbose_name='Срок поставки'),
        ),
        migrations.AddField(
            model_name='tender',
            name='is_trading',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, verbose_name='Проводить торги'),
        ),
        migrations.AddField(
            model_name='tender',
            name='min_step',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Минимальный шаг'),
        ),
        migrations.AddField(
            model_name='tender',
            name='place_of_delivery',
            field=models.CharField(blank=True, max_length=300, verbose_name='Место поставки'),
        ),
        migrations.AddField(
            model_name='tender',
            name='price_request_doc',
            field=models.FileField(blank=True, null=True, upload_to='tender_docs/price_request/%Y/%m/', verbose_name='Запрос КП'),
        ),
        migrations.AddField(
            model_name='tender',
            name='procurement_docs',
            field=models.FileField(blank=True, null=True, upload_to='tender_docs/procurement/%Y/%m/', verbose_name='Закупочная документация'),
        ),
        migrations.CreateModel(
            name='TenderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Количество')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Начальная цена')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tender_items/%Y/%m/', verbose_name='Приложение')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.purchaserequest', verbose_name='Заявка на закупку')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.tender', verbose_name='Конкурс')),
            ],
            options={
                'verbose_name': 'Позиция конкурса',
                'verbose_name_plural': 'Позиции конкурса',
            },
        ),
        migrations.CreateModel(
            name='TenderParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300, verbose_name='Компания')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='procurement.tender', verbose_name='Конкурс')),
            ],
            options={
                'verbose_name': 'Участник конкурса',
                'verbose_name_plural': 'Участники конкурса',
                'unique_together': {('tender', 'company_name')},
            },
        ),
    ]
