# Generated by Django 6.0.1 on 2026-02-01 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_to_approve', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения/доработки'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.purchaserequest', verbose_name='Связанная заявка'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('general', 'Общая'), ('approval', 'Согласование заявки'), ('review', 'Доработка заявки')], default='general', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
    ]
