# Generated by Django 6.0.1 on 2026-02-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_purchaserequest_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='publication_type',
        ),
        migrations.DeleteModel(
            name='TenderParticipant',
        ),
    ]