# Generated by Django 6.0.1 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_remove_tender_publication_type_delete_tenderparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='tasks_sent',
            field=models.BooleanField(default=False, verbose_name='Задачи отправлены'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tasks_removed',
            field=models.BooleanField(default=False, verbose_name='Задачи удалены'),
        ),
    ]