# Generated by Django 6.0.1 on 2026-02-03 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_tender_tasks_sent_tender_tasks_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('validity_date', models.DateField(help_text='Дата окончания действия КП', verbose_name='Действительно до')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tender_proposals/%Y/%m/', verbose_name='Коммерческое предложение')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='procurement.tender', verbose_name='Конкурс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предложение по конкурсу',
                'verbose_name_plural': 'Предложения по конкурсам',
                'ordering': ['-proposal_date'],
                'unique_together': {('tender', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TenderProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Предлагаемая цена')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.tenderproposal', verbose_name='Предложение')),
                ('tender_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.tenderitem', verbose_name='Позиция конкурса')),
            ],
            options={
                'verbose_name': 'Позиция предложения',
                'verbose_name_plural': 'Позиции предложения',
                'unique_together': {('proposal', 'tender_item')},
            },
        ),
    ]
