# Generated by Django 6.0.1 on 2026-02-04 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_tenderproposal_tenderproposalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выбора')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.tenderproposal', verbose_name='Предложение победителя')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_winners', to=settings.AUTH_USER_MODEL, verbose_name='Выбран кем')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='procurement.tender', verbose_name='Конкурс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_tenders', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Победитель конкурса',
                'verbose_name_plural': 'Победители конкурсов',
                'ordering': ['-selected_at'],
            },
        ),
    ]