# Generated by Django 6.0.1 on 2026-02-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_tenderwinner'),
    ]

    operations = [
        # Удаляем складские поля из Material
        migrations.RemoveField(
            model_name='material',
            name='location',
        ),
        migrations.RemoveField(
            model_name='material',
            name='min_stock',
        ),
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='material',
            name='updated_at',
        ),
    ]