# Generated by Django 6.0.1 on 2026-02-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_remove_material_warehouse_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
    ]
