# Generated by Django 6.0.1 on 2026-02-03 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_alter_material_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название/ФИО')),
                ('supplier_type', models.CharField(choices=[('company', 'Юридическое лицо'), ('individual', 'Индивидуальный предприниматель'), ('person', 'Физическое лицо')], default='company', max_length=20, verbose_name='Тип поставщика')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН/ОГРНИП')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Наименование банка')),
                ('bank_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК банка')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет')),
                ('corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счет')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон контактного лица')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email контактного лица')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('specialization', models.TextField(blank=True, verbose_name='Специализация/Категории товаров')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('blocked', 'Заблокирован'), ('new', 'Новый')], default='new', max_length=20, verbose_name='Статус')),
                ('registration_doc', models.FileField(blank=True, null=True, upload_to='supplier_docs/registration/%Y/%m/', verbose_name='Регистрационные документы')),
                ('license_doc', models.FileField(blank=True, null=True, upload_to='supplier_docs/licenses/%Y/%m/', verbose_name='Лицензии и сертификаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['-created_at'],
            },
        ),
    ]
