# Generated by Django 6.0.1 on 2026-02-04 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('general', 'Общая'), ('approval', 'Согласование заявки'), ('review', 'Доработка заявки'), ('contract_approval', 'Согласование договора')], default='general', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название договора')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('end_date', models.DateField(verbose_name='Дата окончания срока договора')),
                ('commercial_proposal', models.FileField(blank=True, null=True, upload_to='contracts/proposals/%Y/%m/', verbose_name='Коммерческое предложение')),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/documents/%Y/%m/', verbose_name='Документ договора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('active', 'Действующий'), ('completed', 'Выполнен'), ('terminated', 'Расторгнут'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_to_approve', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='procurement.supplier', verbose_name='Компания/Поставщик')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='related_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.contract', verbose_name='Связанный договор'),
        ),
    ]
