# Generated by Django 6.0.1 on 2026-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_alter_task_task_type_contract_task_related_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supply_employee',
            field=models.BooleanField(default=False, verbose_name='Сотрудник снабжения'),
        ),
    ]
